version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "update script dependencies"
    reviewers:
      - "oliverkillane"
    groups:
      python-packages:
        patterns:
          - "*"
